[DDA Port] Use precompiled headers to speed up Make build (#1637)
* Precompile the catch header in tests

(cherry picked from commit 6d1841ac67e8a3548d62254926c6598dd867dda4)

* makefile: improve use of precompiled headers

* makefile: add pch to clean target and revert header guard
* define ccache sloppiness for PCH builds
* disble PCH when using ccache with old versions of clang

(cherry picked from commit b31fb271122c246690601bf636e09fcec18b7d68)

* makefile: clean up pch rules

(cherry picked from commit 09e25913641f245e7beaa9ee6586cb40938dc41a)

* Remove precompiled headers and and depfiles at make clean

(cherry picked from commit d9447625e345512a60968513b042af3a4901eec6)

* Explicitly remove precompiled headers by extension

The regex form `{gch,pch,d}` does not work to remove these files on my
Ubuntu linux system. Expanding this into three `rm` statements correctly
removes the files when doing a `make clean`, preventing this error

fatal error: file '.../tests/../src/../pch/main-pch.hpp' has been
modified since the precompiled header 'pch/tests-pch.hpp.pch' was built:
size changed

(cherry picked from commit f9496f29ffd5a8a56b4696a6b02d47d8f6fafbe7)

* Make precompiled Catch2 header ignored by git

(cherry picked from commit 8e95da7704b9ab5f273ca429c966ff51eeed1029)

* Ignore pch/pch.hpp.pch and tests/pch/pch.hpp.pch

(cherry picked from commit bd2d0edbaa3949c546020af5c7d626a7c07386ca)

Co-authored-by: Kevin Granade <kevin.granade@gmail.com>
Co-authored-by: andrei <68240139+andrei8l@users.noreply.github.com>
Co-authored-by: Pär Karlsson <feinorgh@gmail.com>
Co-authored-by: Eric Pierce <wapcaplet88@gmail.com>
Co-authored-by: ZhilkinSerg <ZhilkinSerg@users.noreply.github.com>